name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - "*/package.json"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plugin: ["vite-plugin-tsc-build"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check version change
        id: check_version
        run: |
          VERSION_CHANGE=$(git diff HEAD^ HEAD -- "${{ matrix.plugin }}/package.json" | grep -P "^\+.*\"version\"")
          if [[ -z "$VERSION_CHANGE" ]]; then
            echo "No version change detected for ${{ matrix.plugin }}, skipping publish."
            echo "version_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Version change detected for ${{ matrix.plugin }}, publishing to npm."
            echo "version_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          cd "${{ matrix.plugin }}"
          npm ci

      - name: Build
        run: |
          cd "${{ matrix.plugin }}"
          npm run build

      - name: Publish to npm
        if: steps.check_version.outputs.version_changed == 'true'
        run: |
          cd "${{ matrix.plugin }}"
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
